### ISSUE TITLE
is it possible to use bpy to control third-party addons in blender?

### ISSUE THREAD

**Issue by zhezh** [DIYer22/bpycv#1]
Hi Lei,

I am currently also working on using blender to render some synthetic images for deep learning training, though I am new to blender.
I need to use one addon/plugin naming retarget-bvh to load motion capture data. I wonder if bpy can be used to call third-party addons.

Thanks,
Zhe

**Comment by DIYer22** [comment]
I am new to Blender too, I only started studying blender two weeks ago. So, I don't know the answer, either.

**Comment by zhezh** [comment]
Ha, thanks all the same then.
