### ISSUE TITLE
Render results are not consistent

### ISSUE THREAD

**Issue by Salingo** [DIYer22/bpycv#13]
Hello,

Recently I met a weird bug when trying to build a virtual scanner.

If I directly run `bpycv.render_data()` after blender is initialized, the rendered color image looks like this:
![0-color](https://user-images.githubusercontent.com/15212673/94094722-c7bc4800-fe52-11ea-9e17-8debd63a1c9e.jpg)

However, the result becomes correct if I run `bpycv.render_data()` twice:
![0-color](https://user-images.githubusercontent.com/15212673/94094637-904d9b80-fe52-11ea-9d96-db9f3a7d24f4.jpg)

Same issue can be found on other models, so maybe it is something wrong inside the render function?

**Comment by DIYer22** [comment]
I can't reproduce this bug. I tested on Blender2.83 and Blender2.90, everything look fine.

Could you provide the Blender version and the `.blend` file for me to reproduce bug?

**Comment by Salingo** [comment]
Hi, I have created a repository of my project, please refer to [line 125](https://github.com/Salingo/virtual-3d-scanner/blob/fcf2641ec5746f126839b0e645ea9670efebc1cb/scan_single.py#L125)
On windows, I have to run `render_data` twice to avoid the issue. Not sure how it behaves on Linux.
Thanks!
