### ISSUE TITLE
Cann't find "bpycv'

### ISSUE THREAD

**Issue by MiaoRain** [DIYer22/bpycv#17]
First thanks for your work. Here is a problem about "bpycv'. "bpycv " has been installed in Figure 1 shwon. but still, get the problem in figure 2. how to deal with this? Thanks!

![1](https://user-images.githubusercontent.com/47746159/106721039-1b2f7580-663f-11eb-85f5-35962c29eef2.png)

![2](https://user-images.githubusercontent.com/47746159/106721032-18cd1b80-663f-11eb-9f66-7f3c70dab306.png)

**Comment by DIYer22** [comment]
Maybe, the blender in your `$PATH` is not the one at `~/work/blender/2.90`
Can you provide your blender info by
```
which blender && blender --version
```

**Comment by MiaoRain** [comment]
> Maybe, the blender in your `$PATH` is not the one at `~/work/blender/2.90`
> Can you provide your blender info by
> 
> ```
> which blender && blender --version
> ```
Thanks for replying. Here is the result.
![3](https://user-images.githubusercontent.com/47746159/106741750-18407f00-6657-11eb-9bb7-32d5e1f0987b.png)

**Comment by MiaoRain** [comment]
> Maybe, the blender in your `$PATH` is not the one at `~/work/blender/2.90`
> Can you provide your blender info by
> 
> ```
> which blender && blender --version
> ```
Then how to change the path? Thanks a lot.

**Comment by DIYer22** [comment]
try
```
sudo mv /usr/bin/blender /usr/bin/blender_old
sudo ln -s ~/work/blender/blender /usr/bin/blender
```
