### ISSUE TITLE
How to extend to animation=True case?

### ISSUE THREAD

**Issue by TheShadow29** [DIYer22/bpycv#21]
Thanks for the amazing repository. I was wondering how to use it for instance segmentation in videos?

**Comment by DIYer22** [comment]
`bpycv` not support `animation=True` yet. We will consider support this feature later.

You could try this code temporarily.
```python
for frame_idx in range(120):
    bpy.context.scene.frame_set(bpy.context.scene.frame_current + 1)
    bpycv.render_data()
```

**Comment by TheShadow29** [comment]
@DIYer22 Thanks for your prompt reply!

I am getting this error 
```
'bpy_prop_collection[key]: key "View Layer" not found'
```

Any clue why this could be happening?

Edit: This error seems to be happening on this line: https://github.com/DIYer22/bpycv/blob/master/bpycv/render_utils.py#L55

**Comment by TheShadow29** [comment]
I can confirm replacing the line with `scene.view_layers["View Layer"].cycles` to `scene.view_layers[0].cycles` works out.
