### ISSUE TITLE
How to replace primitives with my own objs in demo.py?

### ISSUE THREAD

**Issue by BostonLobster** [DIYer22/bpycv#22]
I have a bunch of `obj` files, and as the tile says, I want to replace the `bpy.ops.mesh.primitive_cube_add` with my own `obj` files. 

I didn't refer to `ycb_demo.py` because my `obj` files are very simple just like the primitives in demo_vis. They only contain vertices and faces, and with no materials.

How can I achieve this?

**Comment by DIYer22** [comment]
If your `obj` is 3D file like `.obj` or `.ply`, using  `obj = bpycv.load_obj(model_path)`.

**Comment by BostonLobster** [comment]
I have got it done. Thanks for your reply!
