### ISSUE TITLE
Some question about the blender's RGB

### ISSUE THREAD

**Issue by ziyedy** [DIYer22/bpycv#23]
Thanks for your great work, it really helps me a a lot.
Now I meet a problem that I don't know how to change the accuracy RGB such as (0, 0, 1) to the blender's RGB which range in (0, 1).
I read your code and find you have a transform about that, so I really want to know the way I should do to get the accuracy RGB in blender.
Hope to your reply!

**Comment by DIYer22** [comment]
不太明白你说问题指什么, 能用中文重新叙述一下吗?

**Comment by ziyedy** [comment]
感谢回复，就是在渲染得到mask时，我想设置渲染出的mask rgb值为(1, 0, 0)这种RGB具体值（0-255范围），但在blender中设置材质颜色的时候好像没办法直接设置具体的rgb值，需要有一个转化，我不太清除这种转化的规律是什么所以想请教一下

**Comment by DIYer22** [comment]
比较麻烦, 不好文字表述清楚. 要不加个微信语音聊一下? 我微信号
```python
print("gaeaeaka_ayoaunga".replace("a",''))
```
