### ISSUE TITLE
Rendering both semantic & instance segmentation maps

### ISSUE THREAD

**Issue by AvivSham** [DIYer22/bpycv#32]
Hi All,
I saw on other issue how to render semantic segmentation maps by basically change `obj["inst_id"]` to `object_class_id` instead of `object_id`. Is it possible to render both semantic segmentation and instance segmentation in one rendering action? 

As a workaround we can obtain the maps with 2 rendering steps:
- Assign `obj["inst_id"]` with unique value per object, render the scene and save on the side the rgb image and instance segmentation map.
- re-assign `obj["inst_id"]` with unique value per object class and render to obtain the semantic segmentation map.

The procedure above is inefficient as we need to render the scene twice. How can we solve this? (maybe use another filed in `obj` for `class_id`?)

**Comment by DIYer22** [comment]
By setting `obj["inst_id"]` as `object_class_id * 1000+ object_id`, then:

semantic_map = result["inst"] // 1000 
instance_map = result["inst"] % 1000
