### ISSUE TITLE
question regarding <add_img_background>

### ISSUE THREAD

**Issue by shadowwkl** [DIYer22/bpycv#34]
Dear author,

Thanks for implementing this function:
https://github.com/DIYer22/bpycv/issues/24#issuecomment-989646174

But how should I set this <plane> variable as background? Like 
https://github.com/DIYer22/bpycv/blob/c576e01622d87eb3534f73bf1a5686bd2463de97/example/ycb_demo.py#L51-L52
?

Thanks!

**Comment by DIYer22** [comment]
What's the mean of variable? add_img_background only support img_path.

**Comment by shadowwkl** [comment]
> What's the mean of variable? add_img_background only support img_path.

I pass a jpg image path to the function, and it returns a “bpy.data.objects[‘Plane’]” type data.

plane = add_img_background(img_path)

**Comment by DIYer22** [comment]
When call `add_img_background(img_path)`, the img background is added. No need to do anything of the return Plane
