### ISSUE TITLE
demo-inst.png is all zeros?

### ISSUE THREAD

**Issue by singhularAdi** [DIYer22/bpycv#36]
Demo-inst turns out to be all zeros but the final renders seem to be okay, what could be causing this?

![demo-inst](https://user-images.githubusercontent.com/30354613/155862396-8570c792-e16a-45b2-a56c-8f3ae788113c.png)
![demo-vis(inst_rgb_depth)](https://user-images.githubusercontent.com/30354613/155862401-63dd13ce-d698-4ff9-8293-33ce2b7b68d8.jpg)

**Comment by DIYer22** [comment]
`demo-inst.png` is not all zeros, but low brightness.
```python
>>> np.unique(cv2.imread("demo-inst.png", cv2.IMREAD_UNCHANGED))
array([   0, 1001, 1003, 1005, 1007, 1009, 1011, 1013, 1015, 1019, 2002,
       2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018], dtype=uint16)
```
