### ISSUE TITLE
Easy way to get un occluded segmentation maps?

### ISSUE THREAD

**Issue by singhularAdi** [DIYer22/bpycv#37]
I'm trying to get segmentation maps for each object in the scene with and without occlusions, is there an easy way to do this built in? I'm currently using 

`bpy.ops.object.hide_view_set(unselected=True)`

inside the loop that loads up the objects and segmenting them once, and then segmenting the entire image, but this seems to be really inefficient.

**Comment by DIYer22** [comment]
If you only need segmentation maps, you could disable render image. Render image needs long compute.
```
bpycv.render_data(render_image=False)
```

**Comment by singhularAdi** [comment]
That does help to a certain degree. Thanks a tonne!

**Comment by singhularAdi** [comment]
That might help a little bit, thanks.

**Comment by singhularAdi** [comment]
Is it possible to ignore certain objects while segmenting?

**Comment by DIYer22** [comment]
You can set the corresponding object to invisible in render, in view setting
