### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by anferico** [DIYer22/bpycv#4]
I've copy-pasted your code and run it, but the images I get are different from yours (namely, all the meshes are the same color). What could be the reason?

`demo-depth.png`
![demo-depth](https://user-images.githubusercontent.com/30210403/76441942-78d02900-63c0-11ea-987a-d1bff662be14.png)

`demo-inst.png`
![demo-inst](https://user-images.githubusercontent.com/30210403/76441945-7a015600-63c0-11ea-98d4-d4864175e739.png)

`demo-rgb.png`
![demo-rgb](https://user-images.githubusercontent.com/30210403/76441946-7a99ec80-63c0-11ea-80bc-a7fff6e36046.jpg)

`demo-vis(inst|rgb|depth).png`
![demo-vis(inst|rgb|depth)](https://user-images.githubusercontent.com/30210403/76441948-7b328300-63c0-11ea-9a81-caaf2f96e127.jpg)

**Comment by DIYer22** [comment]
It's seems only depth are not corrent. Can you upload your `.blend` file here, so I could debug on the `.blend` file.
