### ISSUE TITLE
Hello, could you please tell me how to generate such data set through this code? I already have the 3D model as follows. I will show that there is no package bpy

### ISSUE THREAD

**Issue by lxwkobe24** [DIYer22/bpycv#46]
![image](https://user-images.githubusercontent.com/67679590/207493221-931ac1a3-dee8-4e52-88e9-25a6ee23ba83.png)
![image](https://user-images.githubusercontent.com/67679590/207493252-5fc5c96d-fca2-46c6-9daa-343680ca1fcc.png)

**Comment by DIYer22** [comment]
Fellow this script, https://github.com/DIYer22/bpycv/blob/master/example/ycb_demo.py

**Comment by lxwkobe24** [comment]
> Fellow this script, https://github.com/DIYer22/bpycv/blob/master/example/ycb_demo.py

the code said: No module name "bpy"
I use pip install bpy is not using
could you tell me how to solve this problem?
Thanks!

**Comment by DIYer22** [comment]
Did you successfully run this install script with test? https://github.com/DIYer22/bpycv#-install
```
# Check bpycv ready
./blender -b -E CYCLES --python-expr "import bpycv,cv2;d=bpycv.render_data();bpycv.tree(d);cv2.imwrite('/tmp/try_bpycv_vis(inst-rgb-depth).jpg', d.vis()[...,::-1])"
```

**Comment by lxwkobe24** [comment]
> Did you successfully run this install script with test? https://github.com/DIYer22/bpycv#-install
> 
> ```
> # Check bpycv ready
> ./blender -b -E CYCLES --python-expr "import bpycv,cv2;d=bpycv.render_data();bpycv.tree(d);cv2.imwrite('/tmp/try_bpycv_vis(inst-rgb-depth).jpg', d.vis()[...,::-1])"
> ```

yes，this test is running successfully!

**Comment by lxwkobe24** [comment]
> Did you successfully run this install script with test? https://github.com/DIYer22/bpycv#-install
> 
> ```
> # Check bpycv ready
> ./blender -b -E CYCLES --python-expr "import bpycv,cv2;d=bpycv.render_data();bpycv.tree(d);cv2.imwrite('/tmp/try_bpycv_vis(inst-rgb-depth).jpg', d.vis()[...,::-1])"
> ```
![try_bpycv_vis(inst-rgb-depth)](https://user-images.githubusercontent.com/67679590/207515189-8032186e-f5d0-4c1d-bac3-8caa4d9b19fe.jpg)

**Comment by DIYer22** [comment]
It's look fine.
try:
```bash
mkdir ycb_demo
cd ycb_demo/

# prepare code and example data
git clone https://github.com/DIYer22/bpycv
git clone https://github.com/DIYer22/bpycv_example_data

cd bpycv/example/

blender -b -P ycb_demo.py

cd dataset/vis/
ls .  # visualize result here
# 0.jpg
```

**Comment by lxwkobe24** [comment]
> 

when i run the "blender -b -P ycb_demo.py", it said the error for this (Command 'blender' not found, but can be installed with:

sudo snap install blender  # version 3.4.0, or
sudo apt  install blender

See 'snap info blender' for additional versions.
)

**Comment by DIYer22** [comment]
try replace `blender` to `./blender -b -P ycb_demo.py` in Blender dir

**Comment by lxwkobe24** [comment]
> try replace `blender` to `./blender -b -P ycb_demo.py` in Blender dir

yes ,it's finish!
![0](https://user-images.githubusercontent.com/67679590/207519440-e7bb1af8-1f03-42ac-ba9a-adf62151fb68.jpg)
But i want to use myself the 3D model  to create dataset like this:
![207493221-931ac1a3-dee8-4e52-88e9-25a6ee23ba83](https://user-images.githubusercontent.com/67679590/207519628-c1f8fa6b-da85-4da8-95b9-5f479cc41967.png)
i really hope you could tell me how to realize !
thanks

**Comment by DIYer22** [comment]
First, learn basic Blender Python API. Than fellow this script, it has comment, https://github.com/DIYer22/bpycv/blob/master/example/ycb_demo.py

**Comment by lxwkobe24** [comment]
> First, learn basic Blender Python API. Than fellow this script, it has comment, https://github.com/DIYer22/bpycv/blob/master/example/ycb_demo.py

ok,thanks a lot!!!!
