### ISSUE TITLE
getting a view from multiple cameras

### ISSUE THREAD

**Issue by oshima-yoppi** [DIYer22/bpycv#49]
Thank you for providing a great library.

I would like to know how to do this when there are multiple cameras.

So far (if I'm not mistaken) I can only get data from the camera viewpoint that exists by default in blender. Please let me know how to get the viewpoints from the cameras I have specified.

I am waiting for your reply.

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。

**Comment by DIYer22** [comment]
Before render:
```
bpy.context.scene.camera = specified_camera
```
