### ISSUE TITLE
why is orthographic camera not supported?

### ISSUE THREAD

**Issue by PimAkker** [DIYer22/bpycv#50]
Hi! Just a quick question: 
In camera_utils.py a check is performed so that the camera is perspective. 
```   
if camd.type != "PERSP":
      raise ValueError("Non-perspective cameras not supported")
```

Why is that? It seems to work fine if i disable this.

Does something happen that i'm not aware of or is this just an untested feature?

Thanks!

**Comment by DIYer22** [comment]
Because the camera intrinsic format of OpenCV does not support orthographic cameras, tasks that require camera intrinsics (such as 6D pose) will result in an error.
