### ISSUE TITLE
Does this tool supports semantic segmentation ?

### ISSUE THREAD

**Issue by SyedShaQutub** [DIYer22/bpycv#6]
Hello,
Thank you for the great tool. I would be really interested to know if this tool : 

a. supports semantic segmentation?
b. can we use our predefined labels like cityscapes label info?

**Comment by DIYer22** [comment]
To (a):    
Supports semantic segmentation, change  [`obj["inst_id"] = inst_id`](https://github.com/DIYer22/bpycv/blob/20ef2214594b9c2ca8cadc15763dbd4961ba0189/example/demo.py#L28)'s `inst_id` to semantic  category id.

To (b):
Just set `inst_id` like Cityscapes's inst_id

**Comment by SyedShaQutub** [comment]
Thank you for your answer.
I have another important question. I guess many would be having the same issue. 
I see the code works on the object level. I have a city model which is basically is a single mesh(object) but has different materials for buildings, streets, etc. Can I create instances based on materials?

**Comment by DIYer22** [comment]
Sorry, not support that.
