### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pilkonimo** [DIYer22/bpycv#7]
Hi, 

I'd like to use your module in one of my projects. Could you please add a license or confirm that the missing license is intended, if one is not allowed to use your code? 

Thanks, 
pilk

**Comment by DIYer22** [comment]
We added [MIT LICENSE](https://github.com/DIYer22/bpycv/blob/master/LICENSE)

**Comment by pilkonimo** [comment]
Thanks!
