### ISSUE TITLE
Will this tool support keypoint annotation?

### ISSUE THREAD

**Issue by darwinharianto** [DIYer22/bpycv#8]
Just like the title, will keypoint function be added later on in this project?

**Comment by DIYer22** [comment]
We have no plans to support key points recently, but you can get keypoint annotation by 6D pose annotation and camera intrinsic like [6d_pose_demo.py](https://github.com/DIYer22/bpycv/blob/master/example/6d_pose_demo.py)
![](https://user-images.githubusercontent.com/10448025/74708759-5e3ee000-5258-11ea-8849-0174c34d507c.png)
